name: quick_bus
description: Fast app to see bus schedules and plan routes

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  geolocator: ^7.7.0
  http: ^0.13.3
  csv: ^5.0.0
  osm_nominatim: ^2.0.1
  flutter_map: ^0.14.0
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.7
  google_polyline_algorithm: ^3.1.0
  flutter_riverpod: ^0.14.0+3
  adaptive_dialog: ^1.1.0
  emoji_picker_flutter: ^1.0.7
  diacritic: ^0.1.3
  proximity_hash: ^2.0.0
  fading_edge_scrollview: ^2.0.0
  introduction_screen: ^2.1.0
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/stops.txt
    - assets/tutorial_bookmarks.png
    - assets/tutorial_saved_plan.png
    - assets/tutorial_starting.png

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "icon/app_icon.png"