name: quick_bus
description: Fast app to see bus schedules and plan routes

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.6.0+16

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_dialog: ^2.2.1
  cached_network_image: ^3.4.0
  csv: ^6.0.0
  diacritic: ^0.1.6
  emoji_picker_flutter: ^3.1.0
  fading_edge_scrollview: ^4.1.1
  flutter_map: ^6.1.0
  flutter_riverpod: ^2.6.1
  geolocator: ^13.0.1
  google_polyline_algorithm: ^3.1.0
  http: ^1.2.2
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  logging: ^1.3.0
  osm_nominatim: ^3.0.1
  proximity_hash: ^2.1.0
  reorderables: ^0.6.0
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/stops.txt
    - assets/tutorial_bookmarks.png
    - assets/tutorial_saved_plan.png
    - assets/tutorial_starting.png

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "icon/app_icon.png"
